# Personal Investment Configuration
# Used by agents to customize analysis and recommendations

investor_profile:
  risk_tolerance: moderate  # conservative, moderate, aggressive
  investment_horizon: long  # short (1-3y), medium (3-7y), long (7+y)
  age: 35
  retirement_target: 65

portfolio_constraints:
  # Position sizing limits
  max_single_position: 0.10      # No more than 10% in one stock
  min_position_size: 0.02         # Minimum 2% position
  max_sector_exposure: 0.25       # Maximum 25% in one sector
  
  # Asset class limits
  min_equity_allocation: 0.40     # Minimum 40% stocks
  max_equity_allocation: 0.80     # Maximum 80% stocks
  min_fixed_income: 0.20          # Minimum 20% bonds
  max_alternatives: 0.20          # Maximum 20% alternatives
  
  # Liquidity requirements
  min_cash_reserve: 0.05          # Keep 5% in cash
  emergency_fund_months: 6        # Separate from investment portfolio

tax_information:
  filing_status: Single           # Single, Married Filing Jointly, etc.
  state: CA                       # State for tax calculations
  tax_bracket_estimated: 0.24     # Federal marginal rate
  
  # Tax preferences
  harvest_losses: true            # Actively harvest tax losses
  defer_gains: true              # Prefer deferring gains
  loss_harvest_threshold: 1000    # Minimum $1000 loss to harvest
  
  # Income sources (for tax planning)
  w2_income: 150000
  bonus_expected: 20000
  investment_income_ytd: 5000

investment_preferences:
  # Asset preferences
  prefer_etfs: true               # ETFs over mutual funds
  prefer_index: true              # Index funds over active
  esg_conscious: false            # ESG investing preference
  
  # Sector preferences
  overweight_sectors:
    - technology
    - healthcare
  underweight_sectors:
    - utilities
    - real_estate
  
  # Geographic allocation
  home_bias: 0.70                # 70% US allocation
  emerging_markets_max: 0.10      # Max 10% EM exposure

rebalancing_rules:
  # Rebalancing triggers
  frequency: quarterly            # quarterly, semi-annual, annual
  threshold_percent: 0.05         # 5% deviation triggers rebalancing
  
  # Cost considerations
  min_trade_size: 500            # Don't rebalance under $500
  tax_aware: true                # Consider tax impact
  
  # Market conditions
  volatility_adjustment: true     # Adjust in high volatility
  avoid_rebalance_in_drawdown: true  # Don't rebalance in crashes

risk_management:
  # Risk limits
  max_portfolio_var_95: 0.15     # Maximum 15% VaR at 95% confidence
  max_drawdown_tolerance: 0.25    # Can tolerate 25% drawdown
  
  # Hedging preferences
  use_options_hedging: false      # Don't use options
  use_stop_losses: false          # Don't use stops
  
  # Stress test thresholds
  fail_threshold: -0.30           # Fail if >30% loss in stress test

benchmarks:
  # Performance comparison
  primary_benchmark: SPY          # S&P 500
  secondary_benchmark: AGG        # Bonds
  custom_benchmark:              # 60/40 portfolio
    SPY: 0.60
    AGG: 0.40

accounts:
  # Account types (affects tax treatment)
  taxable:
    value: 500000
    priority: 1                   # Use first for tax harvesting
  ira:
    value: 250000
    priority: 2                   # Tax-deferred
  roth_ira:
    value: 50000
    priority: 3                   # Tax-free growth

automation_preferences:
  # What to automate
  auto_rebalance: false          # Manual approval required
  auto_tax_harvest: false        # Manual approval required
  auto_reinvest_dividends: true  # Automatic reinvestment
  
  # Alerts
  alert_on_deviation: true       # Alert on 5%+ deviation
  alert_on_risk_breach: true     # Alert if risk limits exceeded
  daily_summary: true            # Daily email summary
  
# Data paths (WSL)
data_paths:
  mcp_servers: "/home/hvksh/investing/"
  price_cache: "/home/hvksh/investing/cache/"
  
# Data paths (Windows)  
config_paths:
  agents: "C:\\Users\\hvksh\\investing\\.claude\\agents\\"
  settings: "C:\\Users\\hvksh\\investing\\.claude\\settings.json"
  
# API Configuration (loaded from .env)
api_keys_source: ".env"  # Never store keys in this file

# Monitoring
monitoring:
  track_decisions: true          # Log all investment decisions
  track_performance: true        # Track performance vs benchmark
  review_frequency: quarterly    # Formal review schedule