# Compliance and Regulatory Rules
# Legal and regulatory constraints for portfolio management

# Account rules
account_rules:
  # Account minimums
  min_account_value: 25000      # $25K minimum for margin/day trading
  min_cash_reserve: 5000        # Keep $5K cash reserve
  max_margin_usage: 0.50        # Max 50% margin usage
  
  # Account types
  account_types:
    taxable:
      wash_sale_applies: true
      tax_reporting: true
      unlimited_contributions: true
    ira:
      wash_sale_applies: false  # No wash sale in IRA
      contribution_limit: 7000   # 2024 limit ($8K if 50+)
      no_margin: true
      no_short_selling: true
    roth_ira:
      wash_sale_applies: false
      contribution_limit: 7000
      income_limits: true       # Phase-out limits apply
      
# Trading rules
trading_rules:
  # Pattern day trading
  pattern_day_trading:
    max_day_trades_per_5_days: 3  # Without $25K
    min_equity_for_unlimited: 25000
    applies_to_margin_accounts: true
    
  # Settlement rules
  settlement:
    stocks_t_plus: 1            # T+1 settlement (as of May 2024)
    options_t_plus: 1           # T+1 for options
    mutual_funds_t_plus: 1      # T+1 for mutual funds
    good_faith_violations_max: 3  # Max before restriction
    
  # Position limits
  position_limits:
    max_options_contracts: 2000  # Per underlying
    max_percentage_of_float: 0.05  # Max 5% of float
    
# Restricted lists
restricted_securities:
  # Never trade these
  blacklist:
    - PRIVATE_EQUITY           # No private securities
    - RESTRICTED_STOCK         # No restricted stock
    - INSIDER_HOLDINGS         # No insider restrictions
    - PENNY_STOCKS            # No OTC/penny stocks
    
  # Require special approval
  caution_list:
    - LEVERAGED_ETFS          # 2x, 3x ETFs need approval
    - INVERSE_ETFS           # Short ETFs need approval  
    - VOLATILITY_PRODUCTS    # VIX, VXX, etc.
    - CRYPTOCURRENCY        # Crypto products
    
  # Concentration limits
  issuer_limits:
    max_single_issuer: 0.10    # Max 10% in one company
    max_related_issuers: 0.15  # Max 15% in related companies
    
# Regulatory reporting
reporting_requirements:
  # Tax reporting
  form_8949: true              # Capital gains/losses
  form_1099: true             # Dividends and distributions
  wash_sale_adjustments: true  # Track and report
  
  # Large position reporting  
  schedule_13f:
    threshold: 100000000       # $100M AUM threshold
    file_quarterly: true
    
  schedule_13g:
    threshold_percent: 0.05    # 5% ownership threshold
    
# International restrictions
international:
  # Withholding taxes
  withholding_rates:
    UK: 0.00                  # UK treaty rate
    Canada: 0.15              # Canada treaty rate
    Japan: 0.10               # Japan treaty rate
    Default: 0.30             # Default withholding
    
  # Restricted countries (OFAC)
  blocked_countries:
    - North Korea
    - Iran
    - Syria
    - Cuba
    - Russia (certain entities)
    
# Options trading levels
options_approval:
  level_1:                    # Covered calls, cash-secured puts
    covered_calls: true
    cash_secured_puts: true
    protective_puts: true
    
  level_2:                    # Long options
    long_calls: true
    long_puts: true
    long_straddles: true
    
  level_3:                    # Spreads
    vertical_spreads: true
    calendar_spreads: true
    diagonal_spreads: true
    
  level_4:                    # Uncovered
    naked_calls: false        # Not approved
    naked_puts: false         # Not approved
    
  current_level: 3            # Current approval level
  
# Best execution requirements
best_execution:
  consider_factors:
    - price
    - speed
    - likelihood_of_execution
    - size_of_order
    - transaction_costs
  document_rationale: true
  
# Suitability requirements
suitability:
  investment_objectives:
    - capital_preservation
    - income
    - growth
    - speculation
  risk_tolerance: moderate     # conservative, moderate, aggressive
  time_horizon: long_term      # short, medium, long
  liquidity_needs: low        # low, medium, high
  
# Audit and compliance
audit_trail:
  retain_records_years: 7     # Keep 7 years of records
  document_decisions: true    # Document all trade rationale
  track_overrides: true       # Track all gate overrides
  quarterly_review: true      # Quarterly compliance review
  
# Gate enforcement
enforcement:
  hard_blocks:               # Cannot override
    - insider_trading
    - wash_sale_violations
    - pattern_day_trading_violation
    - good_faith_violation
    
  soft_blocks:              # Can override with justification
    - concentration_limit
    - risk_limit
    - tax_efficiency
    
  escalation_required:      # Needs second approval
    - position_size_over_5_percent
    - leveraged_products
    - international_restrictions