# Risk Management Policy Limits
# Based on current portfolio metrics and risk tolerance

# Portfolio-level risk limits
portfolio_limits:
  # VaR and risk metrics
  max_daily_var_95: 0.02        # 2% daily VaR (current: ~1.4%)
  max_weekly_var_95: 0.045      # 4.5% weekly VaR
  max_monthly_var_95: 0.09      # 9% monthly VaR
  
  # Drawdown limits
  max_drawdown: 0.20            # 20% maximum drawdown
  max_daily_loss: 0.05          # 5% daily loss triggers immediate review
  
  # Performance thresholds
  min_sharpe: 0.85              # Minimum Sharpe ratio (current: ~0.93)
  min_sortino: 1.0              # Minimum Sortino ratio
  target_sharpe: 1.0            # Target Sharpe for optimization
  
  # Volatility limits
  max_volatility: 0.18          # 18% annual volatility
  min_volatility: 0.05          # 5% min (avoid cash-like returns)

# Position-level limits
position_limits:
  max_single_position: 0.10      # 10% max in any single holding (prevent 25% GEV!)
  min_single_position: 0.005     # 0.5% minimum to avoid tiny positions
  max_sector_concentration: 0.35 # 35% max in any sector
  min_positions: 20              # Minimum 20 positions for diversification
  max_positions: 75              # Maximum 75 positions (manageability)
  
  # Special position types
  max_options_notional: 0.05    # 5% max in options
  max_crypto_allocation: 0.03   # 3% max in crypto
  max_alternatives: 0.15        # 15% max in alternatives

# Correlation and clustering
correlation_limits:
  max_correlation: 0.85         # Max correlation between any two positions
  max_cluster_weight: 0.30      # Max weight in highly correlated cluster
  min_effective_positions: 15   # Minimum "effective" uncorrelated positions

# Stress test thresholds
stress_tests:
  # Historical scenarios
  dot_com_crash: -0.30          # Must survive -30% tech crash
  financial_crisis_2008: -0.35  # Must survive -35% 2008 scenario
  covid_crash: -0.25            # Must survive -25% rapid selloff
  rate_shock_300bp: -0.15      # Must survive +300bp rate shock
  
  # Forward-looking scenarios
  recession_mild: -0.20         # Mild recession scenario
  recession_severe: -0.35       # Severe recession scenario
  inflation_spike: -0.15        # Inflation spike scenario
  
# Alert thresholds (higher than limits for early warning)
alert_thresholds:
  var_95_warning: 0.018         # Alert at 1.8% VaR
  position_concentration_warning: 0.08  # Alert at 8% concentration
  correlation_warning: 0.80     # Alert at 0.80 correlation
  drawdown_warning: 0.15        # Alert at 15% drawdown

# Realism checks (prevent optimizer nonsense)
realism_checks:
  max_expected_sharpe: 3.0      # Reject Sharpe > 3 as unrealistic
  max_expected_return: 0.50     # Reject >50% expected returns
  min_expected_return: -0.10    # Reject strategies expecting losses
  max_turnover: 2.0             # Max 200% annual turnover
  
# Risk budgets by asset class
risk_budgets:
  equity:
    max_var_contribution: 0.015  # Max 1.5% VaR from equities
    target_weight: 0.70         # 70% target allocation
    
  fixed_income:
    max_var_contribution: 0.005  # Max 0.5% VaR from bonds
    target_weight: 0.20         # 20% target allocation
    
  alternatives:
    max_var_contribution: 0.003  # Max 0.3% VaR from alts
    target_weight: 0.10         # 10% target allocation

# Gate override conditions
override_allowed:
  with_justification: true      # Can override with written justification
  requires_confirmation: true   # Requires explicit user confirmation
  max_override_count: 2         # Max 2 overrides per month
  audit_trail: true            # All overrides logged