# Tax Optimization Policy Limits
# Thresholds and rules for tax-efficient portfolio management

# Tax efficiency thresholds
tax_efficiency:
  max_tax_drag: 0.02            # 2% max tax drag on returns
  max_stcg_ratio: 0.30          # Max 30% of gains can be short-term
  min_tax_alpha: 0.005          # Minimum 50bp tax alpha to justify trades
  target_tax_efficiency: 0.95   # Target 95% after-tax return retention

# Capital gains management
capital_gains:
  # Holding period requirements
  ltcg_threshold_days: 365      # Days for long-term treatment
  ltcg_wait_window: 45          # Wait up to 45 days for LTCG
  
  # Harvesting thresholds
  min_loss_harvest: 1000        # Minimum $1,000 loss to harvest
  max_harvest_per_year: 50000   # Max $50,000 harvesting per year
  harvest_threshold_percent: 0.10  # Harvest if down >10%
  
  # Gain realization
  max_gains_per_quarter: 100000  # Max $100K gains per quarter
  gain_offset_ratio: 1.5         # Harvest 1.5x losses vs gains

# Wash sale prevention
wash_sale:
  blackout_days: 31             # 30 days + 1 for safety
  substantially_identical:      # Pairs that trigger wash sale
    - [VOO, SPY]
    - [VTI, ITOT]
    - [IVV, SPY]
    - [QQQ, QQQM]
    - [VEA, IEFA]
    - [VWO, IEMG]
  check_all_accounts: true      # Check across all accounts
  include_spouse: true          # Include spouse accounts

# Tax rates (for optimization)
tax_rates:
  # Federal rates
  ordinary_income:
    single:
      brackets: [[11600, 0.10], [47150, 0.12], [100525, 0.22], [191950, 0.24], [243725, 0.32], [609350, 0.35], [9999999, 0.37]]
    married_joint:
      brackets: [[23200, 0.10], [94300, 0.12], [201050, 0.22], [383900, 0.24], [487450, 0.32], [731200, 0.35], [9999999, 0.37]]
  
  capital_gains_long:
    single:
      brackets: [[47025, 0.00], [518900, 0.15], [9999999, 0.20]]
    married_joint:
      brackets: [[94050, 0.00], [583750, 0.15], [9999999, 0.20]]
      
  capital_gains_short: ordinary  # STCG taxed as ordinary income
  
  # State rates (examples)
  state:
    CA: 0.133                   # California top rate
    NY: 0.109                   # New York top rate
    TX: 0.000                   # Texas (no state tax)
    FL: 0.000                   # Florida (no state tax)
    MA: 0.050                   # Massachusetts flat rate
    MA_stcg: 0.12              # MA special STCG rate
    
  # Additional taxes
  niit: 0.038                  # Net Investment Income Tax
  medicare_surtax: 0.009       # Additional Medicare tax

# Tax lot selection
lot_selection:
  method: HIFO                  # Default: Highest In First Out
  allow_specific_id: true       # Allow specific lot identification
  optimize_by_account: true     # Optimize within each account
  
# Sequencing rules
sequencing:
  harvest_losses_first: true    # Always harvest losses before gains
  realize_ltcg_before_stcg: true  # Prefer LTCG over STCG
  defer_gains_yearend: true     # Defer gains past Dec if possible
  accelerate_losses_yearend: true  # Accelerate losses before yearend
  
# Tax-advantaged strategies
strategies:
  tax_loss_harvesting:
    enabled: true
    frequency: monthly          # Check monthly for opportunities
    min_benefit: 500           # Minimum $500 tax benefit
    
  tax_gain_harvesting:
    enabled: true              # In 0% LTCG bracket
    max_income_for_0_bracket: 47025  # Single filer limit
    
  asset_location:
    enabled: true
    tax_inefficient_in_ira: [bonds, reits]  # Hold in IRA
    tax_efficient_in_taxable: [index_funds, qualified_dividends]
    
  charitable_giving:
    donate_appreciated: true    # Donate appreciated securities
    min_appreciation: 0.30      # Minimum 30% appreciation
    
# Quarterly tax payments
estimated_taxes:
  safe_harbor_percent: 1.10    # 110% of prior year
  current_year_percent: 0.90   # 90% of current year
  payment_dates: ["04-15", "06-15", "09-15", "01-15"]
  
# Year-end planning
year_end:
  review_start_date: "11-01"   # Start year-end planning Nov 1
  final_trades_by: "12-28"     # Complete trades by Dec 28
  required_actions:
    - harvest_losses
    - realize_gains_if_0_bracket
    - check_estimated_payments
    - plan_charitable_giving
    
# Gate override conditions
override_allowed:
  emergency_liquidity: true     # Override for emergency cash needs
  market_opportunity: false     # Cannot override for speculation
  requires_documentation: true  # Must document reason