# Personal Investment Management Configuration
# Customize these settings based on your personal situation

user:
  # Tax configuration - Update with your actual tax rates
  tax:
    federal_bracket: 0.32          # Federal income tax bracket (32%)
    state_rate: 0.093              # State income tax rate (9.3% for CA)
    capital_gains_long: 0.15       # Long-term capital gains rate (15%)
    capital_gains_short: 0.32      # Short-term gains (same as income)
    medicare_surtax: 0.038         # Additional Medicare tax on investment income
    
  # Risk preferences
  risk:
    max_position_size: 0.15        # Maximum 15% in any single position
    min_position_size: 0.01        # Minimum 1% position (avoid tiny positions)
    var_confidence: 0.95           # 95% confidence for VaR calculations
    risk_tolerance: "moderate"     # Options: conservative, moderate, aggressive
    max_drawdown_tolerance: 0.20  # Maximum acceptable drawdown (20%)
    
  # Portfolio management rules
  portfolio:
    rebalance_threshold: 0.05      # Rebalance when allocation drifts by 5%
    min_trade_value: 100           # Minimum trade value in dollars
    tax_loss_harvest_threshold: 1000  # Minimum loss to harvest
    wash_sale_days: 31             # Days to avoid wash sales (IRS rule)
    
  # Data and provider preferences  
  data:
    preferred_provider: "openbb"   # Primary data provider: "openbb" or "yfinance"
    fallback_provider: "yfinance"  # Fallback if primary fails
    quality_threshold: 0.7         # Minimum data quality score (0-1)
    
# System configuration
system:
  # Logging
  logging:
    level: "INFO"                  # Logging level: DEBUG, INFO, WARNING, ERROR
    file: "~/.investing/investing.log"
    max_size_mb: 100               # Max log file size before rotation
    backup_count: 5                # Number of backup logs to keep
    
  # Performance
  performance:
    parallel_workers: 4            # Number of parallel workers for optimization
    timeout_seconds: 300           # Maximum time for optimization (5 minutes)
    
  # Backup
  backup:
    enabled: true
    max_backups: 10                # Keep last 10 backups
    backup_on_change: true         # Only backup when state changes
    
# Asset allocation targets (example - customize to your strategy)
allocation:
  target:
    stocks: 0.70                   # 70% stocks
    bonds: 0.20                    # 20% bonds
    alternatives: 0.10             # 10% alternatives (REITs, commodities, etc.)
  
  # Rebalancing bands (tolerance around target)
  bands:
    stocks: 0.05                   # +/- 5% tolerance
    bonds: 0.03                    # +/- 3% tolerance
    alternatives: 0.02             # +/- 2% tolerance
    
# Watchlist - symbols to track but not necessarily own
watchlist:
  - symbol: "SPY"
    notes: "S&P 500 ETF benchmark"
  - symbol: "VTI"
    notes: "Total market index"
  - symbol: "AGG"
    notes: "Bond aggregate"
  - symbol: "VNQ"
    notes: "Real estate"
  - symbol: "GLD"
    notes: "Gold hedge"